
eventos_bonificacion = [
    "Encontraste una billetera",
    "Te tocó la lotería",
    "Bono inesperado en el trabajo",
    "Vendiste un auto antiguo",
    "Ganaste un concurso",
    "Te devolvieron una deuda",
    "Moneda valiosa en casa",
    "Te ascendieron en el trabajo",
    "Invertiste en criptomonedas",
    "Cheque de regalo",
    "Ganaste una apuesta",
    "Te reembolsaron un gasto",
    "Descubriste un tesoro",
    "Herencia de un tío lejano",
    "Ganaste un sorteo",
    "Te devolvieron el dinero",
    "Premio por buen desempeño",
    "Vendiste entradas revendidas",
    "Encontraste dinero en un cajón",
    "Te pagaron una deuda antigua",
    "Ganaste una beca",
    "Te regalaron acciones",
    "Descubriste una app que paga",
    "Te indemnizaron por daños",
    "Ganaste un viaje y lo vendiste",
    "Te devolvieron la garantía",
    "Encontraste un celular perdido",
    "Te pagaron horas extras",
    "Ganaste un concurso de baile",
    "Te dieron una propina grande"
]

eventos_impuesto = [
    "Chocaste el auto",
    "Te robaron la billetera",
    "Multa por velocidad",
    "Se rompió la heladera",
    "Te aumentaron impuestos",
    "Perdiste tu celular",
    "Dentista de urgencia",
    "Se pinchó una rueda",
    "Te estafaron por internet",
    "Se inundó tu casa",
    "Pagaste una multa",
    "Se quemó la computadora",
    "Te clonaron la tarjeta",
    "Rompió el lavarropas",
    "Te chocaron y pagaste",
    "Perdiste las llaves del auto",
    "Te hackearon la cuenta",
    "Se cayó tu celular al agua",
    "Te cobraron un seguro caro",
    "Se rompió la tele",
    "Multa por mal estacionamiento",
    "Te robaron la bicicleta",
    "Se venció la patente",
    "Te aumentaron la cuota",
    "Rompió el microondas",
    "Te multaron por ruido",
    "Se perdió tu equipaje",
    "Te cobraron de más",
    "Se dañó la playstation",
    "Te multó la tránsito"
]

eventos_neutro = [
    "Leíste un libro en casa",
    "Caminaste por el parque",
    "Ayudaste a cruzar la calle",
    "Viste una película aburrida",
    "Te encontraste con un amigo",
    "Dormiste una siesta",
    "Cocinaste una pizza regular",
    "Lavaste el auto y llovió",
    "Fuiste al gimnasio cerrado",
    "Intentaste tejer y fallaste",
    "Miraste el techo por horas",
    "Ordenaste tu escritorio",
    "Regaste las plantas",
    "Escuchaste música vieja",
    "Llamaste a tu mamá",
    "Sacaste al perro a pasear",
    "Hiciste ejercicio en casa",
    "Limpiaste la cocina",
    "Viste un tutorial útil",
    "Escribiste en un diario",
    "Meditaste por un rato",
    "Reparaste una silla",
    "Duchaste al gato",
    "Doblaste la ropa",
    "Planchaste una camisa",
    "Leíste el diario viejo",
    "Hiciste una lista de tareas",
    "Escuchaste la radio",
    "Revisaste tus redes",
    "Te tomaste un té tranquilo"
]