usuarios = [
    {
        "id": 1,
        "mail": "admin@arcade.com",
        "password": "admin123",
        "rol": "admin",
        "nombre": "Carlos",
        "apellido": "Gomez",
        "edad": 35,
        "nacionalidad": "Argentina",
        "dni": 30111222,
        "fecha_registro": "2024-03-01",
        "activo": True
    },
    {
        "id": 2,
        "mail": "juan@gmail.com",
        "password": "1234",
        "rol": "jugador",
        "nombre": "Juan",
        "apellido": "Perez",
        "edad": 20,
        "nacionalidad": "Argentina",
        "dni": 44111222,
        "fecha_registro": "2024-03-02",
        "activo": True
    },
    {
        "id": 3,
        "mail": "ana@gmail.com",
        "password": "abcd",
        "rol": "jugador",
        "nombre": "Ana",
        "apellido": "Lopez",
        "edad": 25,
        "nacionalidad": "Chile",
        "dni": 33111222,
        "fecha_registro": "2024-03-03",
        "activo": True
    },
    {
        "id": 4,
        "mail": "maria@gmail.com",
        "password": "pass1",
        "rol": "jugador",
        "nombre": "Maria",
        "apellido": "Suarez",
        "edad": 30,
        "nacionalidad": "Uruguay",
        "dni": 29111222,
        "fecha_registro": "2024-03-04",
        "activo": True
    },
    {
        "id": 5,
        "mail": "luis@gmail.com",
        "password": "pass2",
        "rol": "jugador",
        "nombre": "Luis",
        "apellido": "Martinez",
        "edad": 17,
        "nacionalidad": "Argentina",
        "dni": 47111222,
        "fecha_registro": "2024-03-05",
        "activo": True
    },
    {
        "id": 6,
        "mail": "sofia@gmail.com",
        "password": "pass3",
        "rol": "jugador",
        "nombre": "Sofia",
        "apellido": "Ramirez",
        "edad": 22,
        "nacionalidad": "Peru",
        "dni": 45111222,
        "fecha_registro": "2024-03-06",
        "activo": True
    },
    {
        "id": 7,
        "mail": "pedro@gmail.com",
        "password": "pass4",
        "rol": "jugador",
        "nombre": "Pedro",
        "apellido": "Diaz",
        "edad": 28,
        "nacionalidad": "Mexico",
        "dni": 37111222,
        "fecha_registro": "2024-03-07",
        "activo": True
    },
    {
        "id": 8,
        "mail": "laura@gmail.com",
        "password": "pass5",
        "rol": "jugador",
        "nombre": "Laura",
        "apellido": "Fernandez",
        "edad": 19,
        "nacionalidad": "Argentina",
        "dni": 46111222,
        "fecha_registro": "2024-03-08",
        "activo": True
    },
    {
        "id": 9,
        "mail": "diego@gmail.com",
        "password": "d123",
        "rol": "jugador",
        "nombre": "Diego",
        "apellido": "Torres",
        "edad": 40,
        "nacionalidad": "Argentina",
        "dni": 28111222,
        "fecha_registro": "2024-03-09",
        "activo": True
    },
    {
        "id": 10,
        "mail": "lucas@gmail.com",
        "password": "l123",
        "rol": "jugador",
        "nombre": "Lucas",
        "apellido": "Acosta",
        "edad": 23,
        "nacionalidad": "Argentina",
        "dni": 43111222,
        "fecha_registro": "2024-03-10",
        "activo": True
    },
        {
        "id": 11,
        "mail": "valentina@gmail.com",
        "password": "v123",
        "rol": "jugador",
        "nombre": "Valentina",
        "apellido": "Rojas",
        "edad": 21,
        "nacionalidad": "Chile",
        "dni": 42111222,
        "fecha_registro": "2024-03-11",
        "activo": True
    },
    {
        "id": 12,
        "mail": "martin@gmail.com",
        "password": "m123",
        "rol": "jugador",
        "nombre": "Martin",
        "apellido": "Gutierrez",
        "edad": 29,
        "nacionalidad": "Uruguay",
        "dni": 39111222,
        "fecha_registro": "2024-03-12",
        "activo": True
    },
    {
        "id": 13,
        "mail": "camila@gmail.com",
        "password": "c123",
        "rol": "jugador",
        "nombre": "Camila",
        "apellido": "Vega",
        "edad": 18,
        "nacionalidad": "Peru",
        "dni": 48111222,
        "fecha_registro": "2024-03-13",
        "activo": True
    },
    {
        "id": 14,
        "mail": "franco@gmail.com",
        "password": "f123",
        "rol": "jugador",
        "nombre": "Franco",
        "apellido": "Morales",
        "edad": 33,
        "nacionalidad": "Argentina",
        "dni": 32111222,
        "fecha_registro": "2024-03-14",
        "activo": True
    },
    {
        "id": 15,
        "mail": "julieta@gmail.com",
        "password": "j123",
        "rol": "jugador",
        "nombre": "Julieta",
        "apellido": "Castro",
        "edad": 27,
        "nacionalidad": "Mexico",
        "dni": 36111222,
        "fecha_registro": "2024-03-15",
        "activo": True
    },
    {
        "id": 16,
        "mail": "andres@gmail.com",
        "password": "a123",
        "rol": "jugador",
        "nombre": "Andres",
        "apellido": "Silva",
        "edad": 31,
        "nacionalidad": "Chile",
        "dni": 31111222,
        "fecha_registro": "2024-03-16",
        "activo": True
    },
    {
        "id": 17,
        "mail": "paula@gmail.com",
        "password": "p123",
        "rol": "jugador",
        "nombre": "Paula",
        "apellido": "Navarro",
        "edad": 24,
        "nacionalidad": "Argentina",
        "dni": 44119876,
        "fecha_registro": "2024-03-17",
        "activo": True
    },
    {
        "id": 18,
        "mail": "tomas@gmail.com",
        "password": "t123",
        "rol": "jugador",
        "nombre": "Tomas",
        "apellido": "Herrera",
        "edad": 26,
        "nacionalidad": "Uruguay",
        "dni": 40111222,
        "fecha_registro": "2024-03-18",
        "activo": True
    },
    {
        "id": 19,
        "mail": "agustina@gmail.com",
        "password": "ag123",
        "rol": "jugador",
        "nombre": "Agustina",
        "apellido": "Mendez",
        "edad": 22,
        "nacionalidad": "Argentina",
        "dni": 45119876,
        "fecha_registro": "2024-03-19",
        "activo": True
    },
    {
        "id": 20,
        "mail": "nicolas@gmail.com",
        "password": "n123",
        "rol": "jugador",
        "nombre": "Nicolas",
        "apellido": "Cabrera",
        "edad": 34,
        "nacionalidad": "Argentina",
        "dni": 33119876,
        "fecha_registro": "2024-03-20",
        "activo": True
    },
    {
        "id": 21,
        "mail": "florencia@gmail.com",
        "password": "fl123",
        "rol": "jugador",
        "nombre": "Florencia",
        "apellido": "Sosa",
        "edad": 28,
        "nacionalidad": "Peru",
        "dni": 37119876,
        "fecha_registro": "2024-03-21",
        "activo": True
    },
    {
        "id": 22,
        "mail": "jorge@gmail.com",
        "password": "jo123",
        "rol": "jugador",
        "nombre": "Jorge",
        "apellido": "Benitez",
        "edad": 45,
        "nacionalidad": "Paraguay",
        "dni": 27111222,
        "fecha_registro": "2024-03-22",
        "activo": True
    },
    {
        "id": 23,
        "mail": "carolina@gmail.com",
        "password": "ca123",
        "rol": "jugador",
        "nombre": "Carolina",
        "apellido": "Paredes",
        "edad": 32,
        "nacionalidad": "Chile",
        "dni": 34119876,
        "fecha_registro": "2024-03-23",
        "activo": True
    },
    {
        "id": 24,
        "mail": "matias@gmail.com",
        "password": "ma123",
        "rol": "jugador",
        "nombre": "Matias",
        "apellido": "Reyes",
        "edad": 19,
        "nacionalidad": "Argentina",
        "dni": 46119876,
        "fecha_registro": "2024-03-24",
        "activo": True
    },
    {
        "id": 25,
        "mail": "brenda@gmail.com",
        "password": "br123",
        "rol": "jugador",
        "nombre": "Brenda",
        "apellido": "Campos",
        "edad": 23,
        "nacionalidad": "Mexico",
        "dni": 43119876,
        "fecha_registro": "2024-03-25",
        "activo": True
    },
    {
        "id": 26,
        "mail": "sebastian@gmail.com",
        "password": "se123",
        "rol": "jugador",
        "nombre": "Sebastian",
        "apellido": "Ortega",
        "edad": 38,
        "nacionalidad": "Argentina",
        "dni": 29119876,
        "fecha_registro": "2024-03-26",
        "activo": True
    },
    {
        "id": 27,
        "mail": "lucia@gmail.com",
        "password": "lu123",
        "rol": "jugador",
        "nombre": "Lucia",
        "apellido": "Delgado",
        "edad": 21,
        "nacionalidad": "Uruguay",
        "dni": 42119876,
        "fecha_registro": "2024-03-27",
        "activo": True
    },
    {
        "id": 28,
        "mail": "rodrigo@gmail.com",
        "password": "ro123",
        "rol": "jugador",
        "nombre": "Rodrigo",
        "apellido": "Ibarra",
        "edad": 36,
        "nacionalidad": "Chile",
        "dni": 30119876,
        "fecha_registro": "2024-03-28",
        "activo": True
    },
    {
        "id": 29,
        "mail": "daniela@gmail.com",
        "password": "da123",
        "rol": "jugador",
        "nombre": "Daniela",
        "apellido": "Quiroga",
        "edad": 27,
        "nacionalidad": "Argentina",
        "dni": 36119876,
        "fecha_registro": "2024-03-29",
        "activo": True
    },
    {
        "id": 30,
        "mail": "federico@gmail.com",
        "password": "fe123",
        "rol": "jugador",
        "nombre": "Federico",
        "apellido": "Luna",
        "edad": 41,
        "nacionalidad": "Argentina",
        "dni": 28119876,
        "fecha_registro": "2024-03-30",
        "activo": True
    }
]